import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SmoothScroll } from "./components/SmoothScroll";
import Loader from "./components/Loader";
import SessionRepos from "./components/sessionRepos";

import { ViewTransition } from 'react'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Portfólio - Alexsander",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ViewTransition >
      <html lang="pt-br">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <SmoothScroll>
            <SessionRepos>
              <Loader />
              {children}
            </SessionRepos>
          </SmoothScroll>
        </body>
      </html>
    </ViewTransition>
  );
}
